version: 2.1

commands:
  build:
    description: "Build Docker image via Build Tools"
    steps:
      - checkout
      - run: "./.ci/build.sh -f Dockerfile --image ${DOCKER_IMAGE}:${CIRCLE_BUILD_NUM}"
      - run: "docker images"

  save-docker-image:
    description: "Saves a Docker image for future Jobs"
    steps:
      - run: "mkdir -p /tmp/docker-images/"
      - run: "docker save --output /tmp/docker-images/${DOCKER_NAMESPACE}-${DOCKER_IMAGE}-$(docker version -f {{.Server.Arch}})-${CIRCLE_BUILD_NUM}.tar ${DOCKER_NAMESPACE}/${DOCKER_IMAGE}:$(docker version -f {{.Server.Arch}})-${CIRCLE_BUILD_NUM}"
      - run: "ls -lah /tmp/docker-images/"
      - persist_to_workspace:
          root: /tmp
          paths:
            - docker-images/*

  load-docker-image:
    description: "Loads a Docker image"
    steps:
      - attach_workspace:
          at: /tmp/load-images
      - run: "ls -lah /tmp/load-images/"
      - run: "docker load --input /tmp/load-images/${DOCKER_NAMESPACE}-${DOCKER_IMAGE}-$(docker version -f {{.Server.Arch}})-${CIRCLE_BUILD_NUM}.tar"
      - run: "docker images"

executors:
  arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

  amd64:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium

jobs:
  build-image:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - build
      - save-docker-image
    environment:
      DOCKER_IMAGE: multi-arch-demo
      SUPPORTED_ARCHITECTURES: "amd64 arm64"
      GIT_BRANCH: main
      RELEASE_BRANCH: main
      DOCKER_NAMESPACE: drcrow
      FORCE_CI: true

  test-image:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - load-docker-image
    environment:
      DOCKER_IMAGE: multi-arch-demo
      SUPPORTED_ARCHITECTURES: "amd64 arm64"
      GIT_BRANCH: main
      RELEASE_BRANCH: main
      DOCKER_NAMESPACE: drcrow
      FORCE_CI: true


workflows:
  demo:
    jobs:
      - build-image:
          name: build-image-arm64
          architecture: arm64
      - build-image:
          name: build-image-amd64
          architecture: amd64
      - test-image:
          name: test-image-arm64
          requires:
            - build-image-arm64
          architecture: arm64
      - test-image:
          name: test-image-amd64
          requires:
            - build-image-amd64
          architecture: amd64