version: 2.1

commands:
  build:
    steps:
      - checkout
      - run: "./.ci/build.sh -f Dockerfile --image ${DOCKER_IMAGE]:${CIRCLE_SHA1} --push"


executors:
  arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

  amd64:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium

jobs:
  build-and-push:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - build
  environment:
    DOCKER_IMAGE: multi-arch-demo
    SUPPORTED_ARCHITECTURES: "amd64 arm64"
    GIT_BRANCH: $CIRCLE_BRANCH
    RELEASE_BRANCH: main
    DOCKER_NAMESPACE: drcrow


workflows:
  demo:
    jobs:
      - build-and-push:
          architecture: arm64
      - build-and-push:
          architecture: amd64